name: Create Comment on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  create_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function run() {
              const labels = github.context.payload.pull_request.labels.map(label => label.name);
              const defaultLabel = labels.find(label => label === 'patch'); // Use 'patch' as the default label

              const body = `Please review the code carefully before merging and check the following box if the correct type of version is going to be merged\n\n- [ ] This PR means a new version of the package ("${defaultLabel}")`;

              await github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body,
              });
            }

            run();
